
name: 'End-to-End Tests'
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - stable
jobs:
  run-cypress:
    runs-on: ubuntu-latest
    # container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1] # todo: change to [1, 2] - there's only 1 test file now
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - run: pnpm build:docs
      - run: cd packages/e2e && pnpm cypress install

      - uses: cypress-io/github-action@v5.0.0
        with:
          record: true
          parallel: true
          working-directory: packages/e2e
          command: pnpm record
          start: pnpm serve-docs
          tag: ${{ github.event_name }}
          install: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE:
            ${{ github.event.pull_request.title && format('PR {0} - {1}',
            github.event.pull_request.number, github.event.pull_request.title)
            }}